# development:
#   cloud_name: <%= ENV["cloud_name"] %>
#   api_key: <%= ENV["api_key"] %>
#   api_secret: <%= ENV["api_secret"] %>
#   enhance_image_tag: true
#   static_file_support: false
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
#   cloud_name: <%= ENV["cloud_name"] %>
#   api_key: <%= ENV["api_key"] %>
#   api_secret: <%= ENV["api_secret"] %>
#   enhance_image_tag: true
#   static_file_support: true
# test:
#   cloud_name: cloud_name
#   api_key: <%= ENV["API_KEY"] %>
#   api_secret: <%= ENV["API_SECRET"] %>
#   enhance_image_tag: true
#   static_file_support: false

production:
  cloud_name: <%= Rails.application.credentials[Rails.env.to_sym][:cloudinary][:cloud_name] %>
  api_key: <%= Rails.application.credentials[Rails.env.to_sym][:cloudinary][:api_key] %>
  api_secret: <%= Rails.application.credentials[Rails.env.to_sym][:cloudinary][:api_secret] %>
  secret_key_base: <%= Rails.application.credentials.secret_key_base %>
  enhance_image_tag: true
  static_file_support: false