development:
  cloud_name: dqyaazwe7
  api_key: '979745235194575'
  api_secret: DSPznsOdDDBQiFdzC0D2b8FK-Ow
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dqyaazwe7
  api_key: '979745235194575'
  api_secret: DSPznsOdDDBQiFdzC0D2b8FK-Ow
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dqyaazwe7
  api_key: '979745235194575'
  api_secret: DSPznsOdDDBQiFdzC0D2b8FK-Ow
  enhance_image_tag: true
  static_file_support: false